name: Lint

on: [push]

jobs:
  clang-format:

    runs-on: ubuntu-24.04 # latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4

    - name: clang-format lint
      run: |
        ./format-check.py

  check-submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Check Submodules
      uses: awslabs/aws-crt-builder/.github/actions/check-submodules@main
