name: Prepare PECL package

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: "The release nodes for the version."
        required: true

jobs:
  update-version:
    runs-on: ubuntu-20.04 # latest

    steps:

    - name: Checkout Source
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          submodules: recursive

    - name: Get Version
      id: get-version
      run: |
        version_with_v=$(git describe --tags --abbrev=0)
        VERSION=$(echo ${version_with_v} | cut -f2 -dv)
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    - name: Prepare Package Script
      env:
        Notes: ${{ github.event.inputs.release_notes }}
      # Update the version in code and generate the package.
      run: |
        git checkout PECL-release
        python3 dev-scripts/prepare_pecl_release.py --name aws-crt --user aws-crt --email aws-sdk-common-runtime@amazon.com --version ${{ steps.get-version.outputs.VERSION }} --notes $Notes

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pecl_package_${{ steps.get-version.outputs.VERSION }}
        path: awscrt-${{ steps.get-version.outputs.VERSION }}.tgz
        if-no-files-found: error
