name: Release PECL Preparation

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  package:
    name: Prepare package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
          submodules: recursive
          fetch-depth: 0

    - name: Get release tag
      uses: awslabs/aws-crt-builder/.github/actions/release-tag@main
      id: tag

    - name: Prepare Package Script
      run: dev-scripts/prepare-release.sh --name aws-crt --user aws-crt --email aws-sdk-common-runtime@amazon.com --version ${{ steps.tag.outputs.release_tag }} --notes NOTES

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pecl_package_${{ steps.tag.outputs.release_tag }}
        path: awscrt-${{ steps.tag.outputs.release_tag }}.tgz